name: linpad
version: "1.0.2"
summary: "Linpad text editor for Ubuntu with enhanced features"
description: |
  Linpad is a lightweight text editor designed for Ubuntu. It includes file handling, syntax highlighting, dark mode, zoom, word count, and replace functionality.

grade: stable
confinement: devmode  # Use devmode for testing; switch back to strict after confirming tkinter works

architectures:
  - build-on: amd64
  # Uncomment other architectures if needed
  # - build-on: arm64
  # - build-on: armhf
  # - build-on: ppc64el
  # - build-on: s390x
  # - build-on: i386

base: core20

parts:
  linpad:
    plugin: python
    source: .
    stage-packages:
      - python3-tk
      - python3
      - libsqlite3-dev
      - libssl-dev
      - libtk8.6         # Additional tkinter dependency
      - libtcl8.6        # Additional tkinter dependency
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp linpad.py $SNAPCRAFT_PART_INSTALL/usr/bin/linpad
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/linpad

apps:
  linpad:
    command: usr/bin/linpad
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl            # Additional plug for display compatibility
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
