name: linpad
version: "1.0.1-$(git rev-parse --short HEAD)"
summary: "Linpad text editor for Ubuntu with enhanced features"
description: |
  Linpad is a lightweight text editor designed for Ubuntu. It includes file handling, syntax highlighting, dark mode, zoom, word count, and replace functionality.

grade: stable
confinement: strict

base: core20

parts:
  linpad:
    plugin: python
    source: .
    stage-packages:
      - python3-tk  # Ensure tkinter is included
      - python3
      - libsqlite3-dev
      - libssl-dev
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp linpad.py $SNAPCRAFT_PART_INSTALL/usr/bin/linpad
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/linpad

apps:
  linpad:
    command: usr/bin/linpad
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - network
      - network-bind
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
