name: Linpad application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings for max-complexity and max-line-length checks
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest test/

    - name: List project files
      run: |
        ls -R

    - name: Package Application
      run: |
        mkdir -p output
        cp -r ./linpad.py ./output/
        cp ./lin_logo.webp ./output/
        # Copy other necessary files to the output directory
        cp -r ./DEBIAN ./output/  # Copy DEBIAN directory if needed
        cp README.md ./output/     # Include README if needed
        cp LICENSE ./output/       # Include LICENSE file if needed

    - name: Create .deb Package
      run: |
        # Change to the output directory
        cd output
        # Build the .deb package using dpkg-deb
        dpkg-deb --build . linpad.deb
