name: Linpad application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest test/

    - name: List project files
      run: |
        ls -R

    - name: Package Application
      run: |
        mkdir -p output
        cp -r ./linpad.py ./output/
        cp ./lin_logo.webp ./output/
        cp -r ./DEBIAN ./output/
        cp README.md ./output/
        cp LICENSE ./output/

    - name: Create .deb Package
      run: |
        cd output
        dpkg-deb --build . linpad.deb

    - name: Upload .deb Package
      uses: actions/upload-artifact@v3
      with:
        name: linpad-deb-package
        path: output/linpad.deb

    - name: Attest build provenance
      uses: slsa-framework/slsa-github-generator@v1
      with:
        attestation-path: 'output/build.attestation'
