name: Snapcraft CI/CD

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Snapd
        run: sudo apt update && sudo apt install -y snapd

      - name: Install Snapcraft
        run: |
          sudo snap install core
          sudo snap install snapcraft --classic

      - name: Set version dynamically
        run: |
          VERSION="1.0.1-$(git rev-parse --short HEAD)"
          sed -i "s/^version: .*/version: \"$VERSION\"/" snapcraft.yaml

      - name: Build Snap
        run: snapcraft

      - name: Login to Snapcraft
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          echo "${SNAPCRAFT_STORE_CREDENTIALS}" | snapcraft login --with -

      - name: Push Snap to Snap Store
        run: snapcraft push *.snap --release=stable