name: Snapcraft CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Snapd and Snapcraft
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install snapcraft --classic

      - name: Set version dynamically
        run: |
          VERSION="1.0.1-$(git rev-parse --short HEAD)"
          sed -i "s/^version: .*/version: \"$VERSION\"/" snapcraft.yaml

      - name: Build Snap in Destructive Mode
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: "destructive-mode"
        run: snapcraft

      - name: Push Snap to Snap Store
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: snapcraft push *.snap --release=stable