name: Snapcraft CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64, armhf, ppc64el, s390x, i386]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Snapd, Snapcraft, and LXD
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo lxd init --auto

      - name: Set version dynamically
        run: |
          VERSION="1.0.1-$(git rev-parse --short HEAD)"
          sed -i "s/^version: .*/version: \"$VERSION\"/" snapcraft.yaml

      - name: Build Snap for ${{ matrix.architecture }}
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: lxd
        run: snapcraft --use-lxd

      - name: Login to Snapcraft
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          echo "${SNAPCRAFT_STORE_CREDENTIALS}" | snapcraft login --with -

      - name: Push Snap to Snap Store
        if: success()
        run: snapcraft push *.snap --release=stable
